name: CI/CD Pipeline for Maven Project

on:
  # Запускаем пайплайн при каждом пуше в ветки main или master
  push:
    branches: [ main, master ]
  # Или при создании pull request в ветки main или master
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Установка Java и Maven
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Сборка проекта с помощью Maven
      - name: Build with Maven
        run: mvn clean package

      # Выполнение тестов
      - name: Test with Maven
        run: mvn test

      # Деплой на удаленный хост через SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 89.104.69.57
          username: root
          password: 8JD7RDZLZcoyvBfC
          script: |
            cd /root/snap/user/myproject
            git pull origin main
            ./deploy.sh
            mvn install
